// packages/react-app/src/App.tsx
import './App.css';
import {PvrButton, defineCustomElements, PvrComponent} from 'react-library';

defineCustomElements();

function App() {
  return (
    <div className="App">
      <PvrComponent first="Your" last="Name" />
      <PvrButton buttonType="secondary">Secondary button</PvrButton>
    </div>
  );
}

export default App;

// packages/angular-workspace/projects/angular-app/src/app/app.component.ts
import {Component} from '@angular/core';
import {CommonModule} from '@angular/common';
import {RouterOutlet} from '@angular/router';
import {ComponentLibraryModule} from "component-library";

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet, ComponentLibraryModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent {
  title = 'angular-app';
}


<pvr-component first="Your" last="Name"></pvr-component>
<pvr-button buttonType="primary">Click me pls!</pvr-button>
